### ISSUE TITLE
The dataset required in README.txt maybe incorrect?

### ISSUE THREAD

**Issue by SUZhaoyu** [azavea/keras-semantic-segmentation#5]
Hi, the dataset required in `/keras-semantic-segmentation-develop/src/model_training/README.txt` maybe wrong. I tried to run your code and got this error: **/opt/data/datasets/potsdam/4_Ortho_RGBIR/top_potsdam_2_10_RGBIR.tif: No such file or directory**, seems that the program needs **4_Ortho_RGBIR** dataset instead of **3_Ortho_IRRG** as written in the README file.

**Comment by pomadchin** [comment]
@SUZhaoyu I believe it's because of [this](https://github.com/azavea/keras-semantic-segmentation/commit/e6fb15246c4ee31eb76a8349cafa2cb4751146bb) commit.

**Comment by lewfish** [comment]
Thanks for the heads up. The README should now be updated.
